name: 'PostgreSQL Metadata Collector'
description: 'The process of collecting metadata from a database involves gathering information about the database schema, tables, columns, relationships, and constraints. This metadata is then analyzed to identify patterns, trends, and anomalies within the data. Insights are then produced based on the analysis, which can help to inform decision-making, improve data quality, and optimize database performance. This process is commonly used in data profiling, data governance,
 and data management initiatives.'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: true
    default: ''
  target_url:
    description: target url
    required: false
    default: 'https://app.metisdata.io'
  metis_exporter_url:
    description: target url
    required: false
    default: 'https://ingest.metisdata.io'
  foreign_table_name:
    description: foreign_table_name
    required: false
  db_connection_string:
    description: database connection string 
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
