name: 'Metis Analysis'
description: 'Analysis database infrastructure'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: true
    default: ''
  target_url:
    description: target url
    required: false
    default: 'https://app.metisdata.io'
  metis_exporter_url:
    description: target url
    required: false
  foreign_table_name:
    description: foreign_table_name
    required: false
  db_connection_string:
    description: database connection string 
    required: true
    default: ''
  access_key_id:
    description: access_key_id
    required: true
    default: ''
  region:
    description: region
    required: true
    default: ''
  secret_access_key:
    description: secret_access_key 
    required: true
    default: ''
  function_name:
    description: function_name
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
