name: 'Metis Analysis'
description: 'Analysis database infrastructure'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: true
    default: ''
  target_url:
    description: target url
    required: false
    default: 'https://app.metisdata.io'
  db_connection_string:
    description: database connection string 
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: dist/post/index.js
