name: 'PostgreSQL Metadata Collector'
description: 'Collect DB metadata, analyzes it and generate insights'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: true
    default: ''
  target_url:
    description: target url
    required: false
    default: 'https://app.metisdata.io'
  metis_exporter_url:
    description: target url
    required: false
    default: 'https://ingest.metisdata.io'
  get_extra_data:
    description: get_extra_data
    required: false
    default: false
  db_connection_string:
    description: database connection string 
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
